spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    properties:
      hibernate:
        physical_naming_strategy: com.acme.boot.mvc.misc.TablePrefixedSpringPhysicalNamingStrategy
        hbm2ddl:
          auto: create-drop
        format_sql: true
        show_sql: true
