drop table LineItem_tab if exists;
drop table Order_tab if exists;
drop table Product_tab if exists;

create table Product_tab (
   id integer generated by default as identity,
    code varchar(255) not null,
    description varchar(255),
    name varchar(255) not null,
    quantity integer not null check (quantity>=0),
    priceInInr integer not null check (priceInInr>=1),
    version integer not null,
    primary key (id)
);

create table Order_tab (
   id integer generated by default as identity,
    createdAt timestamp,
    quantity integer not null check (quantity>=1),
    priceInInr integer not null check (priceInInr>=1),
    primary key (id)
);

create table LineItem_tab (
   id integer generated by default as identity,
    quantity integer not null check (quantity>=1),
    order_id integer not null,
    product_id integer not null,
    primary key (id)
);

alter table Product_tab
   add constraint UK_1hbchswjl3j24vreoemhjw7er unique (code);

alter table LineItem_tab
   add constraint FKl1s1mw8kv2a04gc1babgcew8q
   foreign key (order_id)
   references Order_tab;

alter table LineItem_tab
   add constraint FK97536kvl32oiag2yftu1gwxwy
   foreign key (product_id)
   references Product_tab;
